language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.2
  - android-28
  - extra-google-m2repository
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_405ece2f58e0_key -iv $encrypted_405ece2f58e0_iv
  -in files/ctf.tar.enc -out files/ctf.tar -d
- tar xvf files/ctf.tar
- chmod +x gradlew
- export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
- export JAVA_HOME=$JAVA8_HOME
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
after_success:
- chmod +x ./generate-apk-release.sh
- "./generate-apk-release.sh"
script:
- cd $TRAVIS_BUILD_DIR/
- "./gradlew assembleRelease"
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
    secure: kYLl7+pKOrpbuePCH83bxgCgXdEzIOyS3JcYfqM5H9JeOGpFC/7zfQvkGZwFw94hf42kU6m0KvoQqKDvy0XhOEPx8LCZeWhPOl9G8WWsiwHaAXEJ6uY6Y6vS2HpjFEsxH6Gn3H2q4Hb6WPgTa0vq3+PPXXhWONz8ohNSp4SS0NK+mzJYFIToVIdo/LQjaeD+M3HcWq4duHPveujIlYjsAGF8c6IoSvC2xcL7F1ZQTL2Nb+CUkw6rKl2j4KnZ3KcWLz5TPFhRD22S+Si+JXxq6CGxh1Xz94e8hEVD4zZbVU9WX2qWCxTxJt31JHfF0UKO9W1Wy6Wre3SPmovGqbNuq0nEWepfA+zY4WmfyiMULoIwteeYKyobph4feWz3QcZJ05aRWhTnguPEsj2yFGDqwuqsuZ5PMdL8+3ODif/+VWQ4Rm39guHeYLtOVXyTiMDcrVSPTWZqubnZ1RwQEp8tplZaPDV3a2dMUfKeUhChF2M0MONCHb3pz51XqJsyY/xqugqLor3lnCJ1abMDvC9/6gbwW5sEmciiTeqb0OXLrTbjb6B+mn73FQWZwxkv9FFM/rjlBEgmTauNS6OObywT7hA87fAXwzh/KU/TyIms3K70YEwnDPVYJZK/03IvMJOoZM8yK2SMHLBMxDQNIgkhQhNmvahp0NmgcTr26WNtbQI=
