language: android

jdk:
  - oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

# Script courtesy of
# https://medium.com/@daggerdwivedi/push-your-apk-to-your-github-repository-from-travis-11e397ec430d#.5v6g5lpxx

before_install:
  - chmod +x gradlew
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
after_success:
  - chmod +x ./upload-gh-pages.sh
  - .scripts/upload-apk.sh
script:
  - ./gradlew clean assembleReleaseTest

#branches:
#  except:
#    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2